//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mu20
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Dog.
    /// </summary>
    //  *** Start programmer edit section *** (Dog CustomAttributes)

    //  *** End programmer edit section *** (Dog CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("DogE", new string[0])]
    [View("DogL", new string[0])]
    public class Dog : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (Dog CustomMembers)

        //  *** End programmer edit section *** (Dog CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "DogE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DogE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DogE", typeof(IIS.Mu20.Dog));
                }
            }
            
            /// <summary>
            /// "DogL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DogL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DogL", typeof(IIS.Mu20.Dog));
                }
            }
        }
    }
}
