//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mu20
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Tail.
    /// </summary>
    //  *** Start programmer edit section *** (Tail CustomAttributes)

    //  *** End programmer edit section *** (Tail CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TailE", new string[0])]
    [View("TailL", new string[0])]
    public class Tail : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (Tail CustomMembers)

        //  *** End programmer edit section *** (Tail CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TailE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TailE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TailE", typeof(IIS.Mu20.Tail));
                }
            }
            
            /// <summary>
            /// "TailL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TailL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TailL", typeof(IIS.Mu20.Tail));
                }
            }
        }
    }
}
